### ISSUE TITLE
'A7' was not declared in this scope

### ISSUE THREAD

**Issue by hardwarehackr** [PaulZC/Iridium_9603N_Mini_Beacon#1]
Hi,

I am interested in building your project so I have started looking at the code.

I have tried compiling it for the M0 and I am getting the error 

"'A7' was not declared in this scope"

Any chance you can suggest how I can resolve it?

Cheers

**Comment by PaulZC** [comment]
Hi there,
Apologies - it is not very clear in the repo. but the code assumes that you have the "Board" set to the Adafruit Feather M0. You can find better instructions in the Iridium_9603N_Beacon repo.:
https://github.com/PaulZC/Iridium_9603_Beacon/blob/master/LEARN.md#how-do-i-upload-the-arduino-code
Please check that you have the Arduino SAMD (32-bits ARM Cortex-M0+) Boards and the Adafruit SAMD (32-bits ARM Cortex-M0+ and Cortex-M4) Boards installed. Then set the board type to Adafruit Feather M0.
Have fun!
Paul

**Comment by hardwarehackr** [comment]
Ah perfect.. that worked.. 

Thanks.. (awesome project BTW...)

**Comment by PaulZC** [comment]
You are welcome!
I must confess, this particular project is a little bit experimental. I have only assembled and tested two boards so far. They both seem to work OK but I would not call this project "fully tried and tested". The full Iridium Beacon has proved very reliable, so this one _should_ be fine too. This design is really just an experiment to see how small I can make the beacon.
Closing this as your issue seems resolved. Please re-open if you have more problems.
All the best.
